# Generated by Django 4.2 on 2024-03-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipecollection',
            old_name='collection',
            new_name='recipe',
        ),
    ]
