# Generated by Django 4.1 on 2024-03-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='vote_type',
            field=models.CharField(blank=True, choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10, null=True),
        ),
    ]
