# Generated by Django 4.1 on 2024-03-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_rating_vote_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='parent_comment',
            field=models.ManyToManyField(blank=True, null=True, to='recipe.rating'),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='vote_type',
            field=models.CharField(blank=True, choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10, null=True),
        ),
    ]
