# Generated by Django 4.1 on 2024-04-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_alter_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_choice',
            field=models.CharField(choices=[('hour', 'hour'), ('minute', 'minute')], default='minute', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
