# Generated by Django 4.1 on 2024-04-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_alter_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_duration_unit',
            field=models.CharField(choices=[('minute', 'minute'), ('hour', 'hour')], default='minute', max_length=10),
        ),
    ]
