# Generated by Django 4.1 on 2024-04-03 15:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0011_rename_time_choice_recipe_time_duration_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='commentvote',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='recipecollection',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together={('author', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('author', 'recipe')},
        ),
    ]
