# Generated by Django 4.1 on 2024-04-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_alter_comment_created_at_alter_recipe_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
