# Generated by Django 4.1 on 2024-04-03 16:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0012_rename_user_comment_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='commentvote',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recipecollection',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'recipe')},
        ),
    ]
