# Generated by Django 4.1 on 2024-05-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_alter_recipe_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'recipe', 'verbose_name_plural': 'recipes'},
        ),
    ]
