# Generated by Django 4.1 on 2024-05-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecollection',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
