# Generated by Django 4.1 on 2024-06-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_alter_recipecollection_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecollection',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7),
        ),
        migrations.AddField(
            model_name='recipecollectionrecipe',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
