version: '3.8'

services:
  web:
    container_name: RecipeAPI
    build:
      context: ./
      dockerfile: Dockfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000

    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  nginx:
      build: ./nginx
      ports:
        - 1337:80
      depends_on:
        - web